apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: irazu
    tier: frontend
    track: stable
spec:
  template:
    metadata:
      labels:
        app: irazu
        tier: frontend
        track: stable
    spec:
      containers:
        - name: react-frontend
          image: coys3000/personal-site:1.27
          env:
          - name: MAILER
            value: "http://backend:4041"
          - name: BUTTERCMS_KEY
            valueFrom:
              secretKeyRef:
                name: butter
                key: buttercms
  replicas: 2
  selector:
    matchLabels:
      app: irazu
      tier: frontend
      track: stable
